const types = {
  SET_ITEM_TEXT: 'SET_ITEM_TEXT',
  ADD_ITEM_TO_LIST: 'ADD_ITEM_TO_LIST',
  REMOVE_ITEM_FROM_LIST: 'REMOVE_ITEM_FROM_LIST',
  REMOVE_ALL_FROM_LIST: 'REMOVE_ALL_FROM_LIST'
};

export default types;